language: node_js
notifications:
  email: false
node_js:
  - '8'
  - '6'
before_script:
  - npm prune
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
before_install: if [[ `npm -v` != 5* ]]; then npm i -g npm@latest; fi
